### ISSUE TITLE
Node Documentation

### ISSUE THREAD

**Issue by robodair** [sudouc/spectrumuc#3]
Define how a node will operate:

- How authentication to firebase will work for nodes
- How the presence system for nodes will work 
- How addition of nodes to the system will work

**Comment by sifex** [comment]
Added node documentation to Standards. @robodair Let me know if it's the formatting you want.

**Preview:**
http://sudo.org.au/standards/#spectrumuc

**Commit:** 
https://github.com/sudouc/standards/commit/8718ac1461c8868574c1018c795586e15d45cb06
